<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Employee;
use App\Models\MasterEmployeeGrade;
use App\Models\MasterEmployeeServiceGrade;
use App\Models\MasterEmployeeStatusEmployment;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Carbon\Carbon;

class EmployeeDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $employees = [
    [
        'nippam' => 750100124,
        'name' => 'ANDJAR ISWANTO',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.081.0.529.000',
        'golongan' => 'C2',
        'tanggal_pegawai_tetap' => '07/22/2008',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '11/15/2007',
    ],
    [
        'nippam' => 660800021,
        'name' => 'WAHYUDI,SH',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.774.996.3.529.000',
        'golongan' => 'C4',
        'tanggal_pegawai_tetap' => '1993-01-05',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1989-01-05',
    ],
    [
        'nippam' => 670300089,
        'name' => 'RIYANTO,SE,AK',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.062.0.529.000',
        'golongan' => 'C3',
        'tanggal_pegawai_tetap' => '1996-03-10',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1996-08-04',
    ],
    [
        'nippam' => 660100027,
        'name' => 'YULIATI',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.060.4.529.000',
        'golongan' => 'C1',
        'tanggal_pegawai_tetap' => '1993-01-05',
        'jenis_kelamin' => 'P',
        'tanggal_capeg' => '1989-01-10',
    ],
    [
        'nippam' => 661200029,
        'name' => 'SUGIANTO',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.775.007.8.521.000',
        'golongan' => 'C1',
        'tanggal_pegawai_tetap' => '1993-01-05',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1989-01-10',
    ],
    [
        'nippam' => 670800042,
        'name' => 'SUGENG, ST',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.083.6.521.000',
        'golongan' => 'C3',
        'tanggal_pegawai_tetap' => '1994-01-12',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1994-01-04',
    ],
    [
        'nippam' => 650800038,
        'name' => 'ANGKAT PRASETYO',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.061.2.529.000',
        'golongan' => 'C1',
        'tanggal_pegawai_tetap' => '1994-01-12',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1994-01-01',
    ],
    [
        'nippam' => 690800044,
        'name' => 'ELI KRISTIANDANI',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.774.987.2.529.000',
        'golongan' => 'C1',
        'tanggal_pegawai_tetap' => '1994-01-12',
        'jenis_kelamin' => 'P',
        'tanggal_capeg' => '1994-01-05',
    ],
    [
        'nippam' => 720900053,
        'name' => 'TUR TJAHJOTO,S.ST',
        'address' => 'PURBALINGGA',
        'npwp_number' => '58.684.484.7.529.000',
        'golongan' => 'C3',
        'tanggal_pegawai_tetap' => '1995-03-05',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1994-01-11',
    ],
    [
        'nippam' => 650500059,
        'name' => 'UTAMI BUDHIANTI,SH',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.776.943.3.529.000',
        'golongan' => 'C3',
        'tanggal_pegawai_tetap' => '07/15/1996',
        'jenis_kelamin' => 'P',
        'tanggal_capeg' => '1995-01-11',
    ],
    [
        'nippam' => 680800064,
        'name' => 'DIANA WIDYASTUTI,SP',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.774.984.9.529.000',
        'golongan' => 'C3',
        'tanggal_pegawai_tetap' => '1996-01-05',
        'jenis_kelamin' => 'P',
        'tanggal_capeg' => '1995-01-11',
    ],
    [
        'nippam' => 730800077,
        'name' => 'WAGIMAN,ST',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.087.7.529.000',
        'golongan' => 'C3',
        'tanggal_pegawai_tetap' => '1996-06-09',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1995-06-12',
    ],
    [
        'nippam' => 690700065,
        'name' => 'RUSIYATI,SH',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.775.009.4.529.000',
        'golongan' => 'C3',
        'tanggal_pegawai_tetap' => '1996-01-05',
        'jenis_kelamin' => 'P',
        'tanggal_capeg' => '1995-01-11',
    ],
    [
        'nippam' => 691200080,
        'name' => 'IRAWAN TRIDESI',
        'address' => 'PURBALINGGA',
        'npwp_number' => '58.684.485.4.529.000',
        'golongan' => 'C3',
        'tanggal_pegawai_tetap' => '07/15/1996',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1996-06-01',
    ],
    [
        'nippam' => 720900125,
        'name' => 'IWAN INFANTRI,SE',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.080.2.501.000',
        'golongan' => 'C2',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => 720900083,
        'name' => 'RAKHMANTO,S.ST',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.097.6.529.000',
        'golongan' => 'C3',
        'tanggal_pegawai_tetap' => '1996-07-10',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1996-06-01',
    ],
    [
        'nippam' => 650900048,
        'name' => 'HARTATI,SPD',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.776.946.6.529.000',
        'golongan' => 'C3',
        'tanggal_pegawai_tetap' => '1994-03-05',
        'jenis_kelamin' => 'P',
        'tanggal_capeg' => '1994-01-11',
    ],
    [
        'nippam' => 700100066,
        'name' => 'ENDAH SUSILOWATI,SH',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.065.3.529.000',
        'golongan' => 'C3',
        'tanggal_pegawai_tetap' => '07/15/1996',
        'jenis_kelamin' => 'P',
        'tanggal_capeg' => '1995-01-11',
    ],
    [
        'nippam' => 650600060,
        'name' => 'YUNI ASTUTI',
        'address' => 'PURBALINGGA',
        'npwp_number' => '58.684.483.9.529.000',
        'golongan' => 'C1',
        'tanggal_pegawai_tetap' => '1996-01-05',
        'jenis_kelamin' => 'P',
        'tanggal_capeg' => '1995-01-11',
    ],
    [
        'nippam' => 670400063,
        'name' => 'ELVI RESTU HARTINI',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.774.997.1.529.000',
        'golongan' => 'C1',
        'tanggal_pegawai_tetap' => '1996-01-05',
        'jenis_kelamin' => 'P',
        'tanggal_capeg' => '1995-01-11',
    ],
    [
        'nippam' => 730300067,
        'name' => 'BERLIANA DYAH LK',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.074.5.529.000',
        'golongan' => 'C2',
        'tanggal_pegawai_tetap' => '06/19/1996',
        'jenis_kelamin' => 'P',
        'tanggal_capeg' => '1995-01-11',
    ],
    [
        'nippam' => 660500070,
        'name' => 'SRI MURNI',
        'address' => 'PURBALINGGA',
        'npwp_number' => '58.684.479.7.527.000',
        'golongan' => 'C2',
        'tanggal_pegawai_tetap' => '07/15/1996',
        'jenis_kelamin' => 'P',
        'tanggal_capeg' => '1995-06-12',
    ],
    [
        'nippam' => 671200072,
        'name' => 'WIDI HARYANI',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.067.9.529.000',
        'golongan' => 'C1',
        'tanggal_pegawai_tetap' => '06/19/1996',
        'jenis_kelamin' => 'P',
        'tanggal_capeg' => '1995-06-12',
    ],
    [
        'nippam' => 660500061,
        'name' => 'SULISTYANINGSIH',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.070.3.521.000',
        'golongan' => 'C2',
        'tanggal_pegawai_tetap' => '1996-08-08',
        'jenis_kelamin' => 'P',
        'tanggal_capeg' => '1995-01-11',
    ],
    [
        'nippam' => 750100078,
        'name' => 'SUSI HERAWATI',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.072.9.521.000',
        'golongan' => 'C1',
        'tanggal_pegawai_tetap' => '1996-08-08',
        'jenis_kelamin' => 'P',
        'tanggal_capeg' => '1995-06-12',
    ],
    [
        'nippam' => 750600079,
        'name' => 'YUNIATI NURHAYAH',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.068.7.529.000',
        'golongan' => 'C1',
        'tanggal_pegawai_tetap' => '1996-08-08',
        'jenis_kelamin' => 'P',
        'tanggal_capeg' => '1995-06-12',
    ],
    [
        'nippam' => 700700101,
        'name' => 'TEGUH KUNTJORO, S.ST',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.096.8.529.000',
        'golongan' => 'C3',
        'tanggal_pegawai_tetap' => '1997-01-04',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1996-04-11',
    ],
    [
        'nippam' => 780800114,
        'name' => 'YULIANTO,SE',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.075.2.529.000',
        'golongan' => 'C2',
        'tanggal_pegawai_tetap' => '1999-11-05',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1998-11-06',
    ],
    [
        'nippam' => 710800100,
        'name' => 'SOPANDI',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.091.9.529.000',
        'golongan' => 'C1',
        'tanggal_pegawai_tetap' => '1997-01-04',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '10/17/1996',
    ],
    [
        'nippam' => 730600075,
        'name' => 'YUNI SETYOWATI,SE',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.063.8.521.000',
        'golongan' => 'C2',
        'tanggal_pegawai_tetap' => '1996-08-08',
        'jenis_kelamin' => 'P',
        'tanggal_capeg' => '1995-06-12',
    ],
    [
        'nippam' => 661100071,
        'name' => 'EDI HARJONO',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.774.999.7.529.000',
        'golongan' => 'C1',
        'tanggal_pegawai_tetap' => '1996-06-09',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1995-06-12',
    ],
    [
        'nippam' => 691000073,
        'name' => 'MOCH.ARIFIN',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.774.991.4.529.000',
        'golongan' => 'C1',
        'tanggal_pegawai_tetap' => '1996-07-10',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1995-06-12',
    ],
    [
        'nippam' => 720700082,
        'name' => 'SUGI ASTUTI',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.069.5.529.000',
        'golongan' => 'C1',
        'tanggal_pegawai_tetap' => '1996-07-10',
        'jenis_kelamin' => 'P',
        'tanggal_capeg' => '1996-06-01',
    ],
    [
        'nippam' => 750100086,
        'name' => 'SUYITNO',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.066.1.521.000',
        'golongan' => 'C1',
        'tanggal_pegawai_tetap' => '10/29/1996',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1996-08-03',
    ],
    [
        'nippam' => 660100108,
        'name' => 'WIDODO PANCA PUTRA',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.774.985.6.529.000',
        'golongan' => 'C1',
        'tanggal_pegawai_tetap' => '10/28/1998',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1998-01-04',
    ],
    [
        'nippam' => 700500050,
        'name' => 'BAMBANG SUBIYAKTO',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.776.950.8.529.000',
        'golongan' => 'C1',
        'tanggal_pegawai_tetap' => '1995-03-05',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1994-01-11',
    ],
    [
        'nippam' => 710700074,
        'name' => 'TRIONO (A)(U & K)',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.064.6.529.000',
        'golongan' => 'C1',
        'tanggal_pegawai_tetap' => '1996-06-09',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1995-06-12',
    ],
    [
        'nippam' => 661200084,
        'name' => 'LEGO PURBOWO',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.776.953.2.529.000',
        'golongan' => 'C1',
        'tanggal_pegawai_tetap' => '10/29/1996',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1996-09-02',
    ],
    [
        'nippam' => 730500085,
        'name' => 'BOEDI HAPSARI',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.071.1.529.000',
        'golongan' => 'C1',
        'tanggal_pegawai_tetap' => '1996-07-10',
        'jenis_kelamin' => 'P',
        'tanggal_capeg' => '1996-09-02',
    ],
    [
        'nippam' => 770400122,
        'name' => 'MAUN SUSENO,A.MD',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.774.981.5.529.000',
        'golongan' => 'C1',
        'tanggal_pegawai_tetap' => '2003-01-02',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2002-05-02',
    ],
    [
        'nippam' => 750900117,
        'name' => 'ADIK PURWO S',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.774.983.1.529.000',
        'golongan' => 'B4',
        'tanggal_pegawai_tetap' => '2000-01-01',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1999-01-03',
    ],
    [
        'nippam' => 700400113,
        'name' => 'SUTARMAN,A.MD',
        'address' => 'PURBALINGGA',
        'npwp_number' => '58.684.481.3.529.000',
        'golongan' => 'B4',
        'tanggal_pegawai_tetap' => '1999-11-05',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1998-11-06',
    ],
    [
        'nippam' => 660100016,
        'name' => 'RATMONO',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.776.941.7.529.000',
        'golongan' => 'B4',
        'tanggal_pegawai_tetap' => '1993-01-05',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1989-01-05',
    ],
    [
        'nippam' => 730600105,
        'name' => 'SUPANDI,A.MD',
        'address' => 'PURBALINGGA',
        'npwp_number' => '58.684.486.2.529.000',
        'golongan' => 'B3',
        'tanggal_pegawai_tetap' => '1998-01-03',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '12/30/1996',
    ],
    [
        'nippam' => 690300039,
        'name' => 'SUWARMAN',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.774.977.3.529.000',
        'golongan' => 'B4',
        'tanggal_pegawai_tetap' => '1994-01-12',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1994-01-01',
    ],
    [
        'nippam' => 700500035,
        'name' => 'TEGUH PRIHATIN',
        'address' => 'PURBALINGGA',
        'npwp_number' => '59.699.820.3.529.000',
        'golongan' => 'B4',
        'tanggal_pegawai_tetap' => '1993-01-05',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1990-01-03',
    ],
    [
        'nippam' => 660600054,
        'name' => 'NURYONO',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.076.0.529.000',
        'golongan' => 'B4',
        'tanggal_pegawai_tetap' => '1995-03-05',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1994-01-11',
    ],
    [
        'nippam' => 640900036,
        'name' => 'SUNANO',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.776.948.2.529.000',
        'golongan' => 'B4',
        'tanggal_pegawai_tetap' => '1993-01-05',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1990-01-05',
    ],
    [
        'nippam' => 671200088,
        'name' => 'UNTUNG WIDADI',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.776.944.1.529.000',
        'golongan' => 'B4',
        'tanggal_pegawai_tetap' => '1996-01-11',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1996-08-04',
    ],
    [
        'nippam' => 661200062,
        'name' => 'HAYATI MULYANINGSIH',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.073.7.529.000',
        'golongan' => 'B3',
        'tanggal_pegawai_tetap' => '1996-01-12',
        'jenis_kelamin' => 'P',
        'tanggal_capeg' => '1995-01-11',
    ],
    [
        'nippam' => 730800123,
        'name' => 'SISWANTO',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.775.005.2.521.000',
        'golongan' => 'B2',
        'tanggal_pegawai_tetap' => '10/20/2006',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2005-07-07',
    ],
    [
        'nippam' => 720800040,
        'name' => 'RAKUM',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.776.938.3.529.000',
        'golongan' => 'B3',
        'tanggal_pegawai_tetap' => '1994-01-12',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1994-01-01',
    ],
    [
        'nippam' => 730500056,
        'name' => 'HANI FAHYUDI',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.776.945.0.529.000',
        'golongan' => 'B3',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => 750700093,
        'name' => 'SUGENG',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.774.908.7.529.000',
        'golongan' => 'B3',
        'tanggal_pegawai_tetap' => '1997-01-07',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1996-01-07',
    ],
    [
        'nippam' => 670400121,
        'name' => 'SARYONO',
        'address' => 'PURBALINGGA',
        'npwp_number' => '58.684.482.1.529.000',
        'golongan' => 'B3',
        'tanggal_pegawai_tetap' => '2000-01-11',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2000-01-03',
    ],
    [
        'nippam' => 751200057,
        'name' => 'RAKHMANTO(A)',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.775.004.5.529.000',
        'golongan' => 'B3',
        'tanggal_pegawai_tetap' => '07/15/1996',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1995-01-01',
    ],
    [
        'nippam' => 660400092,
        'name' => 'MAKMUM',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.775.000.3.529.000',
        'golongan' => 'B3',
        'tanggal_pegawai_tetap' => '1997-01-07',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1996-01-07',
    ],
    [
        'nippam' => 751100094,
        'name' => 'TRIONO (B)(Teknik)',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.774.979.9.529.000',
        'golongan' => 'B3',
        'tanggal_pegawai_tetap' => '1997-01-07',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1996-01-07',
    ],
    [
        'nippam' => 661200037,
        'name' => 'HADI',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.774.990.6.529.000',
        'golongan' => 'B2',
        'tanggal_pegawai_tetap' => '1994-01-09',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1993-01-04',
    ],
    [
        'nippam' => 760300096,
        'name' => 'ANAS SUMARYO',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.776.939.1.529.000',
        'golongan' => 'B3',
        'tanggal_pegawai_tetap' => '1997-01-10',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1996-08-10',
    ],
    [
        'nippam' => 761200097,
        'name' => 'IKSANTO',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.095.0.529.000',
        'golongan' => 'B3',
        'tanggal_pegawai_tetap' => '1997-01-10',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1996-08-10',
    ],
    [
        'nippam' => 710100104,
        'name' => 'SIWAN',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.775.001.1.529.000',
        'golongan' => 'B1',
        'tanggal_pegawai_tetap' => '1998-01-03',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '12/30/1996',
    ],
    [
        'nippam' => 720200095,
        'name' => 'FATHUN',
        'address' => 'PURBALINGGA',
        'npwp_number' => '88.146.394.7.529.000',
        'golongan' => 'B1',
        'tanggal_pegawai_tetap' => '1997-01-10',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1996-08-10',
    ],
    [
        'nippam' => 770900098,
        'name' => 'RIYADI (Teknik)',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.098.4.529.000',
        'golongan' => 'B2',
        'tanggal_pegawai_tetap' => '1997-01-10',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1996-08-10',
    ],
    [
        'nippam' => 670900116,
        'name' => 'YUDI HARYANTO',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.099.2.529.000',
        'golongan' => 'B2',
        'tanggal_pegawai_tetap' => '2000-01-01',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1999-01-03',
    ],
    [
        'nippam' => 770900099,
        'name' => 'SUBUR WINARSO',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.776.949.0.529.000',
        'golongan' => 'B2',
        'tanggal_pegawai_tetap' => '1997-01-10',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1996-08-10',
    ],
    [
        'nippam' => 750400118,
        'name' => 'AFIA WIDODO',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.092.7.529.000',
        'golongan' => 'B2',
        'tanggal_pegawai_tetap' => '09/14/2000',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1999-01-04',
    ],
    [
        'nippam' => 690900111,
        'name' => 'AMIN SUGIARTO',
        'address' => 'PURBALINGGA',
        'npwp_number' => '66.090.986.2.529.000',
        'golongan' => 'B1',
        'tanggal_pegawai_tetap' => '1999-11-05',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1998-11-06',
    ],
    [
        'nippam' => 700100102,
        'name' => 'RASITO (B)',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.775.002.9.529.000',
        'golongan' => 'B1',
        'tanggal_pegawai_tetap' => '1998-01-03',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '12/30/1996',
    ],
    [
        'nippam' => 670600109,
        'name' => 'PUDJIARTO',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.752.093.5.521.000',
        'golongan' => 'A4',
        'tanggal_pegawai_tetap' => '1999-11-05',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '04/27/1998',
    ],
    [
        'nippam' => 701100126,
        'name' => 'RINO',
        'address' => 'PURBALINGGA',
        'npwp_number' => '54.746.766.2.529.000',
        'golongan' => 'B1',
        'tanggal_pegawai_tetap' => '2011-01-01',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2008-01-09',
    ],
    [
        'nippam' => 700900127,
        'name' => 'RIYADI(IKK Kutasari)',
        'address' => 'PURBALINGGA',
        'npwp_number' => '70.461.302.5.529.000',
        'golongan' => 'B1',
        'tanggal_pegawai_tetap' => '2011-01-01',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2008-10-09',
    ],
    [
        'nippam' => 810900129,
        'name' => 'SLAMET AGIL SETIAWAN',
        'address' => 'PURBALINGGA',
        'npwp_number' => '54.542.645.4.529.000',
        'golongan' => 'A4',
        'tanggal_pegawai_tetap' => '2011-01-01',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2010-01-04',
    ],
    [
        'nippam' => 831100130,
        'name' => 'SECHAN',
        'address' => 'PURBALINGGA',
        'npwp_number' => '54.553.986.8.529.000',
        'golongan' => 'A4',
        'tanggal_pegawai_tetap' => '2011-01-07',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2010-01-05',
    ],
    [
        'nippam' => 760100134,
        'name' => 'SUTOYO',
        'address' => 'PURBALINGGA',
        'npwp_number' => '54.505.867.9.529.000',
        'golongan' => 'A4',
        'tanggal_pegawai_tetap' => '2012-01-08',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2011-07-01',
    ],
    [
        'nippam' => 770100132,
        'name' => 'HERMAN',
        'address' => 'PURBALINGGA',
        'npwp_number' => '54.506.045.1.529.000',
        'golongan' => 'A4',
        'tanggal_pegawai_tetap' => '2012-01-08',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '09/30/2010',
    ],
    [
        'nippam' => 690300131,
        'name' => 'EKO MARGIYANTO',
        'address' => 'PURBALINGGA',
        'npwp_number' => '54.630.928.7.529.000',
        'golongan' => 'A4',
        'tanggal_pegawai_tetap' => '2013-01-04',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2010-01-07',
    ],
    [
        'nippam' => 750400133,
        'name' => 'ELAN MUKTI ZAIN',
        'address' => 'PURBALINGGA',
        'npwp_number' => '57.868.904.4.529.000',
        'golongan' => 'A4',
        'tanggal_pegawai_tetap' => '2013-01-03',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '09/30/2010',
    ],
    [
        'nippam' => 781200135,
        'name' => 'ENDRO PURWOKO',
        'address' => 'PURBALINGGA',
        'npwp_number' => '54.506.129.3.529.000',
        'golongan' => 'A4',
        'tanggal_pegawai_tetap' => '2013-01-03',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2012-01-01',
    ],
    [
        'nippam' => 901200136,
        'name' => 'PURWANTO',
        'address' => 'PURBALINGGA',
        'npwp_number' => '54.550.619.8.529.000',
        'golongan' => 'A3',
        'tanggal_pegawai_tetap' => '2013-01-03',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2012-01-01',
    ],
    [
        'nippam' => 790800137,
        'name' => 'MARGONO',
        'address' => 'PURBALINGGA',
        'npwp_number' => '55.668.941.2.529.000',
        'golongan' => 'A3',
        'tanggal_pegawai_tetap' => '2013-01-05',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2012-01-04',
    ],
    [
        'nippam' => 800500138,
        'name' => 'SUYADI',
        'address' => 'PURBALINGGA',
        'npwp_number' => '55.105.875.3.529.000',
        'golongan' => 'A4',
        'tanggal_pegawai_tetap' => '2013-01-05',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2012-01-04',
    ],
    [
        'nippam' => 880600139,
        'name' => 'IMAM TONI PRASETYO',
        'address' => 'PURBALINGGA',
        'npwp_number' => '66.092.230.3.529.000',
        'golongan' => 'B3',
        'tanggal_pegawai_tetap' => '2014-01-04',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2013-01-04',
    ],
    [
        'nippam' => 791000140,
        'name' => 'M.MANSYUR KHOLIQ',
        'address' => 'PURBALINGGA',
        'npwp_number' => '55.122.442.1.529.000',
        'golongan' => 'C2',
        'tanggal_pegawai_tetap' => '2014-01-02',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2013-01-04',
    ],
    [
        'nippam' => 780200141,
        'name' => 'MAR\'IS AMRULAH',
        'address' => 'PURBALINGGA',
        'npwp_number' => '70.461.195.3.529.000',
        'golongan' => 'A4',
        'tanggal_pegawai_tetap' => '2014-01-04',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2013-01-04',
    ],
    [
        'nippam' => 830600142,
        'name' => 'SLAMET SUBEKTI',
        'address' => 'PURBALINGGA',
        'npwp_number' => '70.274.578.7-529.000',
        'golongan' => 'A4',
        'tanggal_pegawai_tetap' => '2014-01-04',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2013-01-04',
    ],
    [
        'nippam' => 800500143,
        'name' => 'SANTOSA',
        'address' => 'PURBALINGGA',
        'npwp_number' => '70.285.648.5.522.000',
        'golongan' => 'B3',
        'tanggal_pegawai_tetap' => '2014-01-04',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2013-01-07',
    ],
    [
        'nippam' => null,
        'name' => 'SUJATNO',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'SUHONO',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'ADI SUSANA',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => 'A3',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2014-01-02',
    ],
    [
        'nippam' => null,
        'name' => 'WILDAN NURUL',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => 'B3',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2014-01-04',
    ],
    [
        'nippam' => null,
        'name' => 'SULISTIYONO',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => 'A4',
        'tanggal_pegawai_tetap' => '2014-01-04',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2013-01-08',
    ],
    [
        'nippam' => null,
        'name' => 'AGUNG CAHYADI',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => 'B2',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2014-01-04',
    ],
    [
        'nippam' => null,
        'name' => 'USHIANA DEVI',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => 'B3',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'P',
        'tanggal_capeg' => '2014-01-04',
    ],
    [
        'nippam' => null,
        'name' => 'DAMAMI',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => 'A3',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2014-01-02',
    ],
    [
        'nippam' => null,
        'name' => 'RAMIDIN',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'PADI SULTONI',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'SAMSURI',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'AMIN SUPRIYATNO',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'SUWAHNAN',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'SUGIHARJO, SE',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => 'C4',
        'tanggal_pegawai_tetap' => '1995-03-05',
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '1994-01-11',
    ],
    [
        'nippam' => null,
        'name' => 'AJI PURWANTO',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => 'A3',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2014-01-04',
    ],
    [
        'nippam' => null,
        'name' => 'SODIKIN',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => 'A3',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2014-01-04',
    ],
    [
        'nippam' => null,
        'name' => 'FAJAR HIDAYAT',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => 'A3',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2014-01-04',
    ],
    [
        'nippam' => null,
        'name' => 'SOPAN WINARDI',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => 'A3',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2014-01-04',
    ],
    [
        'nippam' => null,
        'name' => 'AYUDIA KANTHI L',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => 'B3',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'P',
        'tanggal_capeg' => '2014-01-11',
    ],
    [
        'nippam' => null,
        'name' => 'FITRIA YULIANI',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => 'B2',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'P',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'DESTARA ARNAS',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => 'B2',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2014-01-11',
    ],
    [
        'nippam' => null,
        'name' => 'ANGGORO BAYU A',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'SETIAWAN AJI P',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => 'A2',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'MUNIARJO',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'SAMINGUN',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'Slamet Priyono',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => 'A2',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2014-01-11',
    ],
    [
        'nippam' => null,
        'name' => 'WIDI ASMOKO',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => 'C1',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => '2014-01-11',
    ],
    [
        'nippam' => null,
        'name' => 'JOKO SUMARJONO',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => 'A2',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'BUANG SURIPNO',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'HERI PURNOMO',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => 'A2',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'SUTARYO',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'WISNU KRISMIANTO',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => 'A3',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'SLAMET RIYADI',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'JANUAR RESTU SAPUTRA',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => 'B1',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'IMAM RAKHMANTO',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'MUNGINSIDI',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'PRATIKNO',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'TURMAN',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'SLAMET (SUMBER-SL)',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'KUSUMO SATRIO UTOMO',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => 'B2',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'ERDIONO',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'NUGRO SARTONO',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'KARSONO',
        'address' => 'PURBALINGGA',
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => 'L',
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'EKA SETIAWAN',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'BAGUS WIJAYA DWIASMARA',
        'address' => null,
        'npwp_number' => null,
        'golongan' => 'A3',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'ANGGRIAN WEDHA P',
        'address' => null,
        'npwp_number' => null,
        'golongan' => 'B2',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'HENI MUNFAHIDAH R.',
        'address' => null,
        'npwp_number' => null,
        'golongan' => 'B1',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'SATRIA ADI NUGROHO',
        'address' => null,
        'npwp_number' => null,
        'golongan' => 'B1',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'TRIANA NURLAELI',
        'address' => null,
        'npwp_number' => null,
        'golongan' => 'A3',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'EKO WIGIANTORO',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'WEBY DWI ARYA KUSUMA',
        'address' => null,
        'npwp_number' => null,
        'golongan' => 'B2',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'RANDY MEIRISKA LEKSONO A',
        'address' => null,
        'npwp_number' => null,
        'golongan' => 'B2',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'EKO SUTIKNO',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'SOLEH ALIFA',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'NOVAN AGUS',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'BAYU SAFARGI',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'TRI SETIAWAN',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'PONIDI',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'SUBARMAN',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'HARI SIAM MULYANA',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'HENDRA PURNOMO',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'INDRA KUSUMA',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'PRIYONO',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'SETIAWAN',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'PARYOTO',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'AFIF RIYADI',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'FACHRI MARDLIANA',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'ROFID ALWAN',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'HENDRO PUJATNO',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'HARYANTO',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'KURNIA NIKEN',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'RICA DWI UTAMI PUTRI',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'IVAN YULIAN',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'BAGUS ANDIKA',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'AFIF FATKUROHMAN',
        'address' => null,
        'npwp_number' => null,
        'golongan' => 'B1',
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'INDRA SETIAWAN',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'HARYANTO (OB)',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'EKO RUDI PRIYANTO',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'GESIT VEMPY SAISNA',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
    [
        'nippam' => null,
        'name' => 'WAGIMAN',
        'address' => null,
        'npwp_number' => null,
        'golongan' => null,
        'tanggal_pegawai_tetap' => null,
        'jenis_kelamin' => null,
        'tanggal_capeg' => null,
    ],
];

        $this->command->info("Employees count before import: " . Employee::count());
        $this->command->info("Starting import of " . count($employees) . " employees...");

        // Get default employment status (Pegawai Tetap)
        $statusId = MasterEmployeeStatusEmployment::where("name", "LIKE", "%Tetap%")->first()?->id ?? 1;
        // Default Service Grade (MKG 0 thn)
        $serviceGradeId = MasterEmployeeServiceGrade::where("service_grade", 0)->first()?->id ?? 1;

        $usedEmails = [];

        foreach ($employees as $data) {
            $name = $data["name"];
            $nippam = $data["nippam"] ? (string) $data["nippam"] : null;
            $address = $data["address"];
            $npwp = $data["npwp_number"];
            $gradeName = $data["golongan"];
            $gender = $data["jenis_kelamin"] === "P" ? "female" : "male";
            
            // Normalize dates
            $entryDate = null;
            if ($data["tanggal_pegawai_tetap"]) {
                try {
                    $entryDate = Carbon::parse($data["tanggal_pegawai_tetap"])->format("Y-m-d");
                } catch (\Exception $e) {
                    $entryDate = null;
                }
            }

            // Generate first-name based email
            $nameParts = explode(" ", $name);
            $firstName = Str::slug($nameParts[0] ?? "pegawai" , "");
            if (empty($firstName)) $firstName = "pegawai";

            $email = $firstName . "@pdampurbalingga.co.id";
            
            // Handle duplicate first names for unique emails
            $counter = 1;
            while (in_array($email, $usedEmails) || User::where("email", $email)->where("name", "!=", $name)->exists()) {
                $email = $firstName . $counter . "@pdampurbalingga.co.id";
                $counter++;
            }
            $usedEmails[] = $email;

            // Username still uses slug of full name for internal uniqueness
            $baseUsername = Str::slug($name, "");
            $username = $baseUsername;
            $uCounter = 1;
            while (Employee::where("username", $username)->where("name", "!=", $name)->exists()) {
                $username = $baseUsername . $uCounter;
                $uCounter++;
            }

            // Find Grade ID
            $gradeId = null;
            if ($gradeName) {
                $grade = MasterEmployeeGrade::where("name", $gradeName)->first();
                $gradeId = $grade?->id;
            }

            $this->command->info("Processing: {$name} (NIPPAM: " . ($nippam ?? "NULL") . ")");

            try {
                // Update or Create User
                $user = User::updateOrCreate(
                    ["email" => $email],
                    [
                        "name" => $name,
                        "password" => Hash::make("pdam891706"),
                        "is_verified" => true,
                        "email_verified_at" => now(),
                    ]
                );
                
                // If using Spatie Permission
                if (method_exists($user, "assignRole")) {
                    // Make sure 'user' role exists
                    \Spatie\Permission\Models\Role::firstOrCreate(['name' => 'user', 'guard_name' => 'web']);
                    $user->assignRole("user");
                }

                $this->command->info("User created/updated for {$name} with email: {$email}");

                // Use withoutEvents to prevent automatic NIPPAM generation
                Employee::withoutEvents(function () use ($nippam, $name, $address, $npwp, $email, $username, $gradeId, $serviceGradeId, $statusId, $user, $gender, $entryDate) {
                    Employee::updateOrCreate(
                        ["name" => $name],
                        [
                            "nippam" => $nippam,
                            "address" => $address,
                            "npwp_number" => $npwp,
                            "email" => $email,
                            "office_email" => $email,
                            "username" => $username,
                            "password" => Hash::make("pdam891706"),
                            "basic_salary_id" => $gradeId,
                            "employee_service_grade_id" => $serviceGradeId,
                            "employment_status_id" => $statusId,
                            "users_id" => $user->id,
                            "gender" => $gender,
                            "entry_date" => $entryDate,
                            "leave_balance" => 12,
                        ]
                    );
                });
            } catch (\Exception $e) {
                $this->command->error("Failed to import {$name}: " . $e->getMessage());
            }
        }

        $this->command->info("Import completed successfully!");
    }
}